#Please create the network manually using `docker network create devolon_shopping_cart`
version: '3'

services:
  database:
    build:
      context: docker/database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/data:/var/lib/mysql
    networks:
      - devolon_shopping_cart

  php-fpm:
    build:
      context: docker/php-fpm
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - devolon_shopping_cart

  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - ${APP_PORT}:80
      - ${APP_PORT_SECURE}:443
    networks:
      - devolon_shopping_cart

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    depends_on:
#      - database
#    restart: always
#    ports:
#     - '8080:80'
#    networks:
#     - devolon_shopping_cart
#    environment:
#      PMA_HOST: database

networks:
  devolon_shopping_cart:
